name: Deploy to Yandex Cloud VM
on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        shell: bash
        run: |
          set -euo pipefail
          ssh -o StrictHostKeyChecking=no vorobevavd@158.160.46.65 bash -s <<'EOF'
          set -euo pipefail
          APP_DIR="$HOME/telegram-bot-final"
          REPO_URL="https://github.com/Sparrow-consulting/Proton_bot.git"

          mkdir -p "$APP_DIR"
          cd "$APP_DIR"

          if [ ! -d .git ]; then
            echo ">>> bootstrap: cloning repo into \$APP_DIR"
            git clone "$REPO_URL" .
          fi

          echo ">>> git pull"
          git fetch --all --prune
          git checkout main
          git pull --ff-only origin main

          if [ ! -x ./deploy.sh ]; then
            echo "ERROR: ./deploy.sh отсутствует или не исполняемый"; exit 1
          fi

          echo ">>> run ./deploy.sh"
          ./deploy.sh
          EOF
